Finished the exercises waiting for merge...
Lye-Frozen-Heart/JavaScript-foundations-challenge pull request #1
Opened 2023-11-18 17:52 UTC by Lye-Frozen-Heart

2023-11-19 19:05 UTC, tictools requested changes

2023-11-19 19:05 UTC, tictools commented on exercise_02/getTotalWordsFromString.js
Do you know what does this expression `/[^\p{L}]+/u` mean?

Do you know how `filter` (array method) is working?

🤔

FIX: simplify logic

2023-11-19 19:05 UTC, tictools commented on exercise_07/isTypeOf.js
> +  if (type === Array.isArray() && Array.isArray(valueToBeChecked)) return true;
This statement does not properly work. Have you tested it? 🤔

FIX: needs work

2023-11-20 18:52 UTC, HuevoPlatino commented on exercise_02/getTotalWordsFromString.js
> +  let words = sentence.split(/[^\p{L}]+/u);
You use expressions not explained in class

2023-11-20 18:55 UTC, HuevoPlatino approved these changes

2023-11-21 07:34 UTC, tictools approved these changes

2023-11-21 14:13 UTC, merged